name: Metrics
on:
  # 毎日 0時に更新
  schedule: [{cron: "0 0 * * *"}]
  # 手動実行も可能に
  workflow_dispatch:
  # マージ時にも更新
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # すでに設定したトークンを使用（プライベートリポジトリも集計）
          token: ${{ secrets.PROFILE_TOKEN }}
          
          # 画像の保存名
          filename: metrics.languages.svg
          
          # 基本データ（ヘッダーなど）は非表示にし、言語のみ表示
          base: ""
          
          # 言語プラグインを有効化
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
