name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # 毎日深夜0時に更新
  workflow_dispatch: # 手動でも実行できるようにする

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write # 画像を保存するための書き込み権限

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # テーマ設定 (solarized, radical, tokyonight, default など変更可能)
          # ここでは画像に近いダーク系テーマを指定します
          THEME: radical
